// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TurnoWebApi.Models;

public partial class TTurno
{
    public int? Id { get; set; }

    public string? Fecha { get; set; }

    public string? Hora { get; set; }


    public string? Cliente { get; set; }
    //[Column("Fecha_Cancelacion")] //
    //public DateTime? FechaCancelacion { get; set; }
    //[Column("Motivo_Cancelacion")] //
    //public string? MotivoCancelacion { get; set; }


}