// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TurnoWebApi.Models;

namespace TurnoWebApi.Models
{
    public partial class turnos_db﻿Context
    {
        private Iturnos_db﻿ContextProcedures _procedures;

        public virtual Iturnos_db﻿ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new turnos_db﻿ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public Iturnos_db﻿ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class turnos_db﻿ContextProcedures : Iturnos_db﻿ContextProcedures
    {
        private readonly turnos_db﻿Context _context;

        public turnos_db﻿ContextProcedures(turnos_db﻿Context context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_CONSULTAR_SERVICIOSResult>> SP_CONSULTAR_SERVICIOSAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_CONSULTAR_SERVICIOSResult>("EXEC @returnValue = [dbo].[SP_CONSULTAR_SERVICIOS]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_CONTAR_TURNOSAsync(string fecha, string hora, OutputParameter<int?> ctd_turnos, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterctd_turnos = new SqlParameter
            {
                ParameterName = "ctd_turnos",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = ctd_turnos?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "fecha",
                    Size = 10,
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "hora",
                    Size = 8,
                    Value = hora ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterctd_turnos,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_CONTAR_TURNOS] @fecha = @fecha, @hora = @hora, @ctd_turnos = @ctd_turnos OUTPUT", sqlParameters, cancellationToken);

            ctd_turnos.SetValue(parameterctd_turnos.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_INSERTAR_DETALLESAsync(int? id_turno, int? id_servicio, string observaciones, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "id_turno",
                    Value = id_turno ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "id_servicio",
                    Value = id_servicio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "observaciones",
                    Size = 200,
                    Value = observaciones ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_INSERTAR_DETALLES] @id_turno = @id_turno, @id_servicio = @id_servicio, @observaciones = @observaciones", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_INSERTAR_TURNOAsync(string fecha, string hora, string cliente, OutputParameter<int?> id_turno, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterid_turno = new SqlParameter
            {
                ParameterName = "id_turno",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = id_turno?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "fecha",
                    Size = 10,
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "hora",
                    Size = 5,
                    Value = hora ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "cliente",
                    Size = 100,
                    Value = cliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterid_turno,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_INSERTAR_TURNO] @fecha = @fecha, @hora = @hora, @cliente = @cliente, @id_turno = @id_turno OUTPUT", sqlParameters, cancellationToken);

            id_turno.SetValue(parameterid_turno.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
